version: 2.1 # use CircleCI 2.1
jobs: # basic units of work in a run
  registry:
    executor: rena-executor
    steps:
      - run:
          name: run image registry
          command: |
            sudo mkdir -p /etc/apt/keyrings

            # configure docker for the insecure registry
            echo "Docker info before"
            docker info
            echo "Debug : Populate registry"
            sudo sh -c 'echo "{ \"insecure-registries\":[\"0.0.0.0:5000\"] }" >> /etc/docker/daemon.json'
            sudo systemctl restart docker
            echo "Docker info after"
            docker info

            # Run the registry
            echo "Start registry"
            docker run -d -p 5000:5000 --name registry registry

            # pull images from quay
            echo "Pull Images"
            echo "Pull skupper-router:latest"
            docker pull quay.io/skupper/skupper-router:latest
            echo "Pull service-controller:master"
            docker pull quay.io/skupper/service-controller:master
            echo "Pull config-sync:master"
            docker pull quay.io/skupper/config-sync:master
            echo "Pull vflow-collector:master"
            docker pull quay.io/skupper/vflow-collector:master
            echo "Pull site-controller:master"
            docker pull quay.io/skupper/site-controller:master

            # tag images for local registry
            echo "Tag images"
            echo "Tag image skupper-router"
            docker tag quay.io/skupper/skupper-router:latest 0.0.0.0:5000/skupper-router:latest
            echo "Tag image service-controller"
            docker tag quay.io/skupper/service-controller:master 0.0.0.0:5000/service-controller:master
            echo "Tag image config-sync"
            docker tag quay.io/skupper/config-sync:master 0.0.0.0:5000/config-sync:master
            echo "Tag image vflow-collector"
            docker tag quay.io/skupper/vflow-collector:master 0.0.0.0:5000/vflow-collector:master
            echo "Tag image site-controller"
            docker tag quay.io/skupper/site-controller:master 0.0.0.0:5000/site-controller:master

            # push images
            echo "Push images"
            echo "Push image skupper-router"
            docker push 0.0.0.0:5000/skupper-router:latest
            echo "Push image service-controller"
            docker push 0.0.0.0:5000/service-controller:master
            echo "Push image site-controller"
            docker push 0.0.0.0:5000/site-controller:master
            echo "Push image config-sync"
            docker push 0.0.0.0:5000/config-sync:master
            echo "Push image vflow-collector"
            docker push 0.0.0.0:5000/vflow-collector:master

            # Update OS and install ifconfig
            sudo apt update
            sudo apt install net-tools

            # ifconfig to pick the correct IP
            for inet in $(ifconfig | grep mtu | cut -d ":" -f 1); do ip=$(ifconfig ${inet} | grep "inet " | awk -F " " '{print $2}'); \
              if [ "${ip}" != "" ]; then echo ${inet}=${ip};fi; curl -v http://${ip}:5000/v2/_catalog/; done

      - minikube-install
      - minikube-start-medium

commands:
  minikube-install:
    description: Installs the minikube executable onto the system.
    steps:
      - run:
          command: >-
            curl -Lo minikube
            https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 &&
            chmod +x minikube && sudo
            mv minikube /usr/local/bin/
          name: Install Minikube Executable

  minikube-start-medium-with-registry:
    description: Starts the minikube service, with 2 CPU and 2 GiB and with insecure registry
    steps:
      - run:
          command: >-
            minikube start --vm-driver=docker --cpus 2 --memory 2048 --insecure-registry 0.0.0.0:5000
          name: Start Minikube Cluster

executors:
  rena-executor:
    machine:
      image: ubuntu-2004:current
      resource_class: medium

workflows:
  version: 2
  build-workflow:
    jobs:
      - registry
