version: 2.1 # use CircleCI 2.1
jobs: # basic units of work in a run
  registry:
    executor: rena-executor
    steps:
      - run:
          name: run image registry
          command: |
            sudo mkdir -p /etc/apt/keyrings

            # Run the registry
            docker run -d -p 5000:5000 --name registry registry

            # Update OS and install ifconfig
            sudo apt update
            sudo apt install net-tools

            # ifconfig to pick the correct IP
            for inet in $(ifconfig | grep mtu | cut -d ":" -f 1); do ip=$(ifconfig ${inet} | grep "inet " | awk -F " " '{print $2}'); \
              if [ "${ip}" != "" ]; then echo ${inet}=${ip};fi; curl http://${ip}:5000/v2/_catalog/; done

executors:
  rena-executor:
    machine:
      image: ubuntu-2004:current
    resource_class: medium

workflows:
  version: 2
  build-workflow:
    jobs:
      - registry
